QT.multimedia_private.VERSION = 5.15.0
QT.multimedia_private.name = QtMultimedia
QT.multimedia_private.module =
QT.multimedia_private.libs = $$QT_MODULE_LIB_BASE
QT.multimedia_private.includes = $$QT_MODULE_INCLUDE_BASE/QtMultimedia/5.15.0 $$QT_MODULE_INCLUDE_BASE/QtMultimedia/5.15.0/QtMultimedia
QT.multimedia_private.frameworks =
QT.multimedia_private.depends = core_private gui_private multimedia
QT.multimedia_private.uses = pulseaudio
QT.multimedia_private.module_config = v2 internal_module
QT.multimedia_private.enabled_features = alsa gstreamer_1_0 gstreamer gstreamer_app gstreamer_encodingprofiles gstreamer_gl linux_v4l openal pulseaudio
QT.multimedia_private.disabled_features = directshow evr gpu_vivante gstreamer_0_10 gstreamer_imxcommon gstreamer_photography resourcepolicy wasapi wmf wmsdk wshellitem
QMAKE_INCDIR_GSTREAMER = /home/seame-four/rpi/sysroot/usr/include/gstreamer-1.0 /home/seame-four/rpi/sysroot/usr/include/orc-0.4 /home/seame-four/rpi/sysroot/usr/include/gstreamer-1.0 /home/seame-four/rpi/sysroot/usr/include/glib-2.0 /home/seame-four/rpi/sysroot/usr/lib/arm-linux-gnueabihf/glib-2.0/include
QMAKE_DEPENDS_GSTREAMER_APP_CC = GSTREAMER
QMAKE_DEPENDS_GSTREAMER_APP_LD = GSTREAMER
QMAKE_DEPENDS_GSTREAMER_GL_CC = GSTREAMER
QMAKE_DEPENDS_GSTREAMER_GL_LD = GSTREAMER
QMAKE_INCDIR_GSTREAMER_GL = /home/seame-four/rpi/sysroot/usr/lib/arm-linux-gnueabihf/gstreamer-1.0/include /home/seame-four/rpi/sysroot/usr/include/libdrm
QMAKE_INCDIR_OPENAL = /home/seame-four/rpi/sysroot/usr/include/AL
QMAKE_DEFINES_PULSEAUDIO = _REENTRANT
QMAKE_INCDIR_PULSEAUDIO = /home/seame-four/rpi/sysroot/usr/include/glib-2.0 /home/seame-four/rpi/sysroot/usr/lib/arm-linux-gnueabihf/glib-2.0/include
QMAKE_LIBS_ALSA = -lasound
QMAKE_LIBS_GSTREAMER = -L/home/seame-four/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lgstaudio-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstpbutils-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0
QMAKE_LIBS_GSTREAMER_APP = -lgstapp-1.0
QMAKE_LIBS_GSTREAMER_GL = -lgstgl-1.0
QMAKE_LIBS_OPENAL = -L/home/seame-four/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lopenal
QMAKE_LIBS_PULSEAUDIO = -L/home/seame-four/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lpulse-mainloop-glib -lpulse -lglib-2.0
