/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201907221047.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/IPCStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace commonapi {

IPCStubDefault::IPCStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(IPC::getInterfaceVersion()) {
}

const CommonAPI::Version& IPCStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

IPCStubRemoteEvent* IPCStubDefault::initStubAdapter(const std::shared_ptr< IPCStubAdapter> &_adapter) {
    CommonAPI::Stub<IPCStubAdapter, IPCStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}


void IPCStubDefault::canDataMethod(const std::shared_ptr<CommonAPI::ClientId> _client, IPC::CanData _frame, canDataMethodReply_t _reply) {
    (void)_client;
    (void)_frame;
    IPC::CanData canFrame = {};
    _reply(canFrame);
}




IPCStubDefault::RemoteEventHandler::RemoteEventHandler(IPCStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace commonapi
} // namespace v1
